# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rb/GitHub/adpcm-xq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rb/GitHub/adpcm-xq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rb/GitHub/adpcm-xq/CMakeFiles /Users/rb/GitHub/adpcm-xq//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rb/GitHub/adpcm-xq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adpcm-lib

# Build rule for target.
adpcm-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 adpcm-lib
.PHONY : adpcm-lib

# fast build rule for target.
adpcm-lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/build
.PHONY : adpcm-lib/fast

#=============================================================================
# Target rules for targets named adpcm-xq-exe

# Build rule for target.
adpcm-xq-exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 adpcm-xq-exe
.PHONY : adpcm-xq-exe

# fast build rule for target.
adpcm-xq-exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-xq-exe.dir/build.make CMakeFiles/adpcm-xq-exe.dir/build
.PHONY : adpcm-xq-exe/fast

adpcm-dns.o: adpcm-dns.c.o
.PHONY : adpcm-dns.o

# target to build an object file
adpcm-dns.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-dns.c.o
.PHONY : adpcm-dns.c.o

adpcm-dns.i: adpcm-dns.c.i
.PHONY : adpcm-dns.i

# target to preprocess a source file
adpcm-dns.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-dns.c.i
.PHONY : adpcm-dns.c.i

adpcm-dns.s: adpcm-dns.c.s
.PHONY : adpcm-dns.s

# target to generate assembly for a file
adpcm-dns.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-dns.c.s
.PHONY : adpcm-dns.c.s

adpcm-lib.o: adpcm-lib.c.o
.PHONY : adpcm-lib.o

# target to build an object file
adpcm-lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-lib.c.o
.PHONY : adpcm-lib.c.o

adpcm-lib.i: adpcm-lib.c.i
.PHONY : adpcm-lib.i

# target to preprocess a source file
adpcm-lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-lib.c.i
.PHONY : adpcm-lib.c.i

adpcm-lib.s: adpcm-lib.c.s
.PHONY : adpcm-lib.s

# target to generate assembly for a file
adpcm-lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-lib.dir/build.make CMakeFiles/adpcm-lib.dir/adpcm-lib.c.s
.PHONY : adpcm-lib.c.s

adpcm-xq.o: adpcm-xq.c.o
.PHONY : adpcm-xq.o

# target to build an object file
adpcm-xq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-xq-exe.dir/build.make CMakeFiles/adpcm-xq-exe.dir/adpcm-xq.c.o
.PHONY : adpcm-xq.c.o

adpcm-xq.i: adpcm-xq.c.i
.PHONY : adpcm-xq.i

# target to preprocess a source file
adpcm-xq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-xq-exe.dir/build.make CMakeFiles/adpcm-xq-exe.dir/adpcm-xq.c.i
.PHONY : adpcm-xq.c.i

adpcm-xq.s: adpcm-xq.c.s
.PHONY : adpcm-xq.s

# target to generate assembly for a file
adpcm-xq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adpcm-xq-exe.dir/build.make CMakeFiles/adpcm-xq-exe.dir/adpcm-xq.c.s
.PHONY : adpcm-xq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... adpcm-lib"
	@echo "... adpcm-xq-exe"
	@echo "... adpcm-dns.o"
	@echo "... adpcm-dns.i"
	@echo "... adpcm-dns.s"
	@echo "... adpcm-lib.o"
	@echo "... adpcm-lib.i"
	@echo "... adpcm-lib.s"
	@echo "... adpcm-xq.o"
	@echo "... adpcm-xq.i"
	@echo "... adpcm-xq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

